### ISSUE TITLE
Cabinet rack diagram is not resizeable 

### ISSUE THREAD

**Issue by pavelignatov** [jgraph/drawio#3052]
**Describe the bug**
Rack cabinet diagram is not resizeable

**To Reproduce**
1. Check rack cabinet
2. Resize it
3. Resize is not working

**Expected behavior**
Resize is working 

**Screenshots**
<img width="975" alt="image" src="https://user-images.githubusercontent.com/26165528/190699836-74b5ec96-9f28-44cb-9cf1-442b5878d009.png">

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version 20.30.0

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome, safari, firefox

**Comment by rmundel** [comment]
Same here

**Comment by egrimate** [comment]
The rack containers should be fixed in the next release

**Comment by davidjgraph** [comment]
Internal commit https://github.com/jgraph/drawio-dev/commit/5a2bcccd51d219c47ba35e3bd0abafa5f3ec0697

**Comment by szwedoman** [comment]
Rack cabinet diagram is not resizeable in 20.5.2 release
![image](https://user-images.githubusercontent.com/7964864/200200472-dc963059-06fe-4d30-bc10-c98796e86fd4.png)

**Comment by kenm-4682** [comment]
Hello, this is not actually fixed yet.

See issue from Nov 2022:
https://github.com/jgraph/drawio/issues/3164

Latest test:

draw.io version (In the Help->About menu of the draw.io editor):
draw.io version 20.8.23

Desktop (please complete the following information):
OS: macOS Ventura
Replicated on both browsers:
Chrome Version 110.0.5481.177 (Official Build) (arm64))
Safari Version 16.3
