### ISSUE TITLE
Chrome - Drawio Intense Lag

### ISSUE THREAD

**Issue by ThePieMonster** [jgraph/drawio#3636]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Describe the bug**
Drawio will lag out when there are more than ~20 images present in the diagram. 

**To Reproduce**
1. Create a Drawio diagram with at least 20 images
2. Use the Chrome browser latest version
3. Try clicking or panning around the diagram

**Expected behavior**
The web page / diagram can be moved around with lagging out.

**draw.io version (In the Help->About menu of the draw.io editor):**

- draw.io version [21.3.6]

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome Version 113.0.5672.127]

**Comment by davidjgraph** [comment]
Can you attach the diagram you're testing with?

**Comment by imtrobin** [comment]
I'm seeing the same issue with 21.4.0

**Comment by davidjgraph** [comment]
Yet still no diagram....

**Comment by imtrobin** [comment]
I can't share that cos there's confidential info but it's  over 10 images.

**Comment by imtrobin** [comment]
Is there something specific in the images you want to look at? Image size etc?

**Comment by ThePieMonster** [comment]
I can upload a test diagram that I made which is showing signs of the slowdown. @davidjgraph
[Test_Diagram.zip](https://github.com/jgraph/drawio/files/11908804/Test_Diagram.zip)

**Comment by mararad** [comment]
The attached file is 3.07 MB and it lags a bit.
Tested in Chrome Version 114.0.5735.199 (Official Build) (64-bit) and FF, diagrams.net 21.6.1 and Win 10 Pro.

**Comment by jeroenvriesman** [comment]
I see the same lagging in version v22.1.16, quite extreme/unworkable lag on a simple windows laptop (i5-1135G7, 2.4GHz, 8GB). Windows 10 enterprise 22H2.
To reproduce just create new diagram from cloud/IBM/any-example.
The lag takes the from of actual pauses I need to wait for when I try to move the drawio window.

**Comment by jeroenvriesman** [comment]
Update: I just tried version 20.8.16, same diagrams. No lag at all.
I will trey in-between versions to find the version which introduces this behaviour.

**Comment by davidjgraph** [comment]
If you disable extras->automatic bacukup on 24.2.5?

**Comment by jeroenvriesman** [comment]
Disabling automatic backup doesn't make any difference.

**Comment by jeroenvriesman** [comment]
Another update: 22.1.16 on linux does not have this problem.
Could it be possible dat https://github.com/jgraph/drawio-desktop/issues/1433 is introducing this behavior? Since it's the only change which would be interacting with the windows os differently compared to linux. A bit of a guess. If you have a windows no-installer 22.1.16 with this feature disabled I can test it. (does the code use feature flags?)

**Comment by davidjgraph** [comment]
Thanks for the detailed analysis. The key problem here is still the ability to reproduce the issue.

It be that that release has some specific signature that an anti-virus doesn't like and scans it constantly. The fact you see it on Win and not Linux suggests something down that route. We have several million installs on win, yet just one report on a simple diagram.

Also, I don't think your issue is the same one as the OP. The result is the same, but the earlier posts are about large diagrams and those issues are fixed.

You're welcome to log another ticket, but this all sounds like a one-off issue specific to your machine, unfortunately.

**Comment by jeroenvriesman** [comment]
Hi again.

Whatever newer version of drawio I try, the problem persists.

I've attached an example drawing which shows the window-movement lag. It's just one of the IBM examples copied 5 times.

22.1.15 works perfectly well, al never versions have a performance problem which is easy to see, just try to move the drawio window on a windows PC.

The PC is definitely not a high performance one, but drawio 22.1.15 ans below works perfectly well.
[lag_test_drawing.zip](https://github.com/user-attachments/files/15607230/lag_test_drawing.zip)

**Comment by alderg** [comment]
The above test case does not slow down window movement on macOS in the online and desktop versions 24.4.14 and 24.4.13. Please include the draw.io version number for your environment, as well as desktop or online, your operating system and browser and versions.

**Comment by jeroenvriesman** [comment]
Ok, new ticket created. 
https://github.com/jgraph/drawio/issues/4458
