### ISSUE TITLE
Exporting PDF when landscape and portrait orientations coexist in same document

### ISSUE THREAD

**Issue by jagjordi** [jgraph/drawio#428]
While exporting a PDF that contains landscape and portrait pages the output is wrong. My intuition is that it should export a pdf that has variable orientation according to the drawio orientations but the result is wired pdf with cropped pages. See example
[OperationDiagram_wrong.pdf](https://github.com/jgraph/drawio/files/3169388/OperationDiagram_wrong.pdf)

**Comment by HerveSC** [comment]
Same issue there. I can't upload the .drawio file, but here is my export too.
[pdf-export-bug.pdf](https://github.com/jgraph/drawio/files/3345535/pdf-export-bug.pdf)

Any update about this issue?

**Comment by dougcooper** [comment]
This is also an issue when printing and portrait appears to be the preferred orientation. 
Test case: 1) 1st page is landscape, 2) 2nd page is portrait.
Actual result: all pages are portrait

**Comment by davidjgraph** [comment]
It's quite a block of work to implement this, unless we get a PR, it won't go in anytime soon.

**Comment by ashrafteleb** [comment]
Fixed, will be available in the next release

**Comment by HerveSC** [comment]
This issue is still not fixed in v12.9.13

[pdf_export_bug.zip](https://github.com/jgraph/drawio/files/4485739/pdf_export_bug.zip)

**Comment by ashrafteleb** [comment]
We cannot reproduce. Can you please explain the steps?
[pdf_export_bug.pdf](https://github.com/jgraph/drawio/files/4486754/pdf_export_bug.pdf)

**Comment by HerveSC** [comment]
I've done more testing and the fact is that this issue remains only in the Desktop version (12.9.13). If I try on your online version, no issue.

The steps I follow:
- Open the .drawio file
- File > Export as > PDF
- Choose a filename

**Comment by ashrafteleb** [comment]
Yes, desktop app doesn't have this feature yet. The library we are using is not compatible with Electron

**Comment by berkdemir** [comment]
How come this issue is marked as completed? It's still there.

**Comment by davidjgraph** [comment]
@berkdemir File a new issue with environment details and recreation steps.
