### ISSUE TITLE
OneDrive for Business

### ISSUE THREAD

**Issue by awendland** [jgraph/drawio#8]
First off, thanks for making such a wonderful application! It's been such a great tool for throwing ideas together over the past couple of years.

I've recently switched from using Google Drive, which worked flawlessly with this awesome app, over to OneDrive for Business, where I am now running into some problems. Fundamentally, I think the problem is on Microsoft's end [with their mess of Azure AD vs. personal accounts](https://blogs.technet.microsoft.com/enterprisemobility/2016/09/15/cleaning-up-the-azure-ad-and-microsoft-account-overlap/). However, until they get that fixed it's thrown onto the app developers to handle the mayhem.

To help on that end, I was taking a look at [war/js/diagramly/OneDriveClient.js#L171](https://github.com/jgraph/draw.io/blob/master/war/js/diagramly/OneDriveClient.js) and it appears that Draw.io currently uses the [OneDrive Authentication and Sign-in for personal accounts](https://dev.onedrive.com/auth/msa_oauth.htm). To support business accounts, it looks like a couple changes/additions would need to be made:
1. [Register Draw.io with OneDrive for Business](https://dev.onedrive.com/auth/aad_oauth.htm#register-your-app-with-azure-active-directory)
2. Add an option to go through a similar OAuth flow to the current OneDrive support, but with a [changed set of base URLs that are set up for business accounts](https://dev.onedrive.com/auth/aad_oauth.htm#step-1-log-in-and-get-an-authorization-code). As far as I can tell, this shouldn't be all that different than the personal account login flow (I think it's exactly the same besides the different URLs).

I don't think there are any other discrepancies between account types besides [login](https://dev.onedrive.com/auth/readme.htm).

Thanks again for making this sweet tool!

**Comment by davidjgraph** [comment]
The story here is we tried the registration process for OneDrive for Business and after about 4 hours just gave up. It's simply horrific. Maybe we could find one of the OneDrive team to guide us, but otherwise we'll try to make time (and hope they just improve it in the meantime).

**Comment by awendland** [comment]
@davidjgraph That's too bad to hear :( Hopefully with Microsoft's new unified auth system that they're working on this whole nightmare will get much better.

**Comment by rgregg** [comment]
@davidjgraph Sorry you had so much trouble with getting auth for ODB working. Were you using the new https://apps.dev.microsoft.com experience? Shoot me a message and I'll be happy to work with your team to get draw.io working with ODB in addition to ODC.

**Comment by davidjgraph** [comment]
@rgregg Thanks Ryan for getting in touch. I tried https://dev.onedrive.com/auth/aad_oauth.htm#register-your-app-with-azure-active-directory last time (it was some time ago). I guess https://azure.microsoft.com/en-us/documentation/articles/active-directory-appmodel-v2-overview/ is what I should be reading first? Thanks.

**Comment by coupalm** [comment]
Any development on this feature? It would be very usefull for business users. Thanks.

**Comment by davidjgraph** [comment]
We've a round of integration updates scheduled, but that's down on Gaudenz's todo and that's a long todo...

**Comment by davidpearce** [comment]
+1 this would be useful for my company too. Thanks

**Comment by davidjgraph** [comment]
Please vote using the thumbs up on the original comment.

**Comment by miqui** [comment]
👍 please add ODB to draw.io ! thanks!

**Comment by davidjgraph** [comment]
"Please vote using the thumbs up on the original comment.", i.e. don't write "me too"

**Comment by drawnword** [comment]
Interestingly, Microsoft is promoting draw.io on a Onedrive for Business page... 

https://products.office.com/en-us/onedrive-for-business/apps-that-work-with-onedrive?tab=Consumer

**Comment by davidjgraph** [comment]
If you want the feature vote it up. If you really want the feature implement it yourself and submit a PR. Sarcastic comment waste our time. This is a free tool, open source tool. Either add something constructive...

**Comment by alexshak** [comment]
Hey guys, just checking in on this issue - any chance its on the road-map to fix? Stuck in a OneDrive world, trying to find a good collaborative diagram tool... and I'm hoping you're the one ;).

**Comment by davidjgraph** [comment]
We track votes on [feature requests at uservoice](https://draw.uservoice.com/forums/266072-feature-requests), Github to more for development issues. It's better to vote there to raise the priority. [This is the relevant item to vote on](https://draw.uservoice.com/forums/266072-feature-requests/suggestions/18479014-ability-to-save-to-sharepoint-and-onedrive-for-bus).

**Comment by keunes** [comment]
Hi all,
I gave my support over at Uservoice. Just wanted to chip in here to say that I can log in to OneDrive Business, add Draw.io as an app and give it all needed permissions. It is a problem when it starts asking for authorisation after I have selected the folder (?)

**Comment by davidjgraph** [comment]
Under help->about what version are you seeing?

**Comment by keunes** [comment]
Which help? Of Draw.io? In the web-interface I see 6.7.11

**Comment by davidjgraph** [comment]
Yes. It's 6.8.0 you need for OneDrive for Business accounts to work, you need a refresh.

**Comment by keunes** [comment]
Awesome. Did you just update it? 'cause I just opened draw.io this afternoon :)
Thanks in any case! 👍 :)

**Comment by davidjgraph** [comment]
Yes, the release was about 45 minutes ago, good timing :).

**Comment by von-taylor-avalara** [comment]
works great for me as well - thanks for the support!

**Comment by dudicp** [comment]
It seems to work on files located in the employee personal folders but not on files found under company folders. 
I'm being able to select the file from the browse dialog but when selecting the file and clicking on 'open', I'm getting the following error: "The resource could not be found."

**Comment by KazuyDarklight** [comment]
Ditto, if I save to my own individual storage under OneDrive for Business then everything is fine, but while I can navigate to and see the files and folders of the SharePoint OneDrive for Business storage areas that I have access to with no problem, if I actually try to open any file or save a new file to one of the folders then I get "The Resource could not be found."

**Comment by alderg** [comment]
We're using the latest version of the graph API (v1.0) and the picker (v7.2). They don't seem to support SharePoint OneDrive for Business storage.

**Comment by ronvanpol** [comment]
I too can't seem to open or save files with ODB. I am able to authenticate and browse through company files, but opening them as well as saving files to the company folders result in an error message. Would love to see it fixed

**Comment by ronvanpol** [comment]
Same here

**Comment by momamene** [comment]
It seems that the problem is not solved currently. This issue needs to be reopened.

**Comment by JohnBloom** [comment]
I just found this thread after trying for hours to get OneDrive to work for diagrams shared by multiple people. We have a requirement to use OneDrive for company diagrams and I have been trying to use a central place in OneDrive to save the files. I was able to create a sharepoint group that I can access for draw.io but when I try to open the files in the group it says "The resource could not be found." 

Does anyone have a workaround? My current workaround is to have people copy the files to their own OneDrive and make changes and then copy them back. Its not great but it will work for now.

**Comment by mechanic22** [comment]
I can conform we are having the same issue. Also the "Shared with me" doesn't show up in open from one drive. We tried copying and pasting into the open from URL and that should the "The resource could not be found" error.

**Comment by davidjgraph** [comment]
Trello thread for sharepoint specific part at https://trello.com/c/HjxEcmYb/283-add-onedrive-for-business-on-sharepoint-support. I'll close this since the OneDrive for Business part is implemented, it's the sharepoint part that isn't.

**Comment by davidjgraph** [comment]
Sharepoint integration fixed in 9.2.9

**Comment by BobVul** [comment]
Is the issue @mechanic22 mentioned fixed? I can't see files "shared with me" via business onedrive/sharepoint, so the only way to open those files is to download and upload to draw.io...

**Comment by davidjgraph** [comment]
This issue is primarily to track OneDrive for Business Online and Sharepoint integration. That is implemented at a high level so the issue is marked as closed.

If there is another issue, please open as another issue.

**Comment by tomoveu** [comment]
We just installed drawio as add-ins for our Office 365 for Business and Sharepoint files are not available. Further more we get an error, when trying to access Sharepoint. 

Screenshot - https://designfirstee-my.sharepoint.com/:i:/g/personal/dimi_designfirst_ee/EQ49pZdNeE1AnBVMuN7EIMcB55h4AWglKbQplTnZEeu9cw?e=rlPZ3J

The issue discussed here sounds similar.

**Comment by elesmera11** [comment]
Has this really been resolved? I am still unable to access my OneDrive for Business shared files via the online version of draw.io.

**Comment by davidjgraph** [comment]
It is resolved. Please take specific issues to https://groups.google.com/forum/#!forum/drawio

**Comment by crisher0219** [comment]
So, one way around this, while not ideal, is to sync your ODB to your local machine. Then, use the device option within Draw.io, but simply select the ODB synced folders at that point.

**Comment by davidjgraph** [comment]
Again, this issue tracks a feature request, that request is implemented. If you have an additional issue relating to a bug, please post a new issue with reproduction steps.
