### ISSUE TITLE
Getting 401 while authorizing Google Drive

### ISSUE THREAD

**Issue by ShivamS136** [jgraph/drawio#942]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Description:**
I am trying to create a new diagram, so when I use Google Drive for storage then it asks to authorize while I have already authorized. Then when I click on authorize then list of signed-in accounts appear, when I choose account then it shows permissions to allow. When I click allow then I am getting **401** hence not able to create a new diagram with Google drive as storage.

**To Reproduce:**
1. Go to 'Create new diagram'
2. Click on 'Authorize' for google drive
3. Click on Email account
4. Click on Allow
4. See error it's 401

**Expected behavior:**
It should have authorized google drive and my new diagram should be saved in the drive.

**Screenshots:**
![image](https://user-images.githubusercontent.com/32218762/83264112-4377f200-a1dd-11ea-87e8-3b76b5c0a79d.png)

**draw.io version:**

- 13.1.7

**Desktop:**
 - OS: Windows 10
 - Browser : Google Chrome
 - Version: 83.0.4103.61 (Official Build) (64-bit)

**Comment by tianhecloud** [comment]
exactly the same issue. please help.

**Comment by davidjgraph** [comment]
Should be fixed if you reload.

**Comment by tianhecloud** [comment]
> Should be fixed if you reload.

no luck. still 401.

**Comment by davidjgraph** [comment]
Need to clear cache. Does it work on another browser?

**Comment by tianhecloud** [comment]
> Need to clear cache. Does it work on another browser?
clear cache on my chrome browser does not work.

and I just made a new installation of a Chromium browser and tried again.
Still the same 401.

**Comment by davidjgraph** [comment]
Then something is caching further up in your network, just have to wait until that clears.

**Comment by tianhecloud** [comment]
it works now.  Thanks.

**Comment by ShivamS136** [comment]
Previously it wasn't working even after the refresh, Now it is.
